apiVersion: v1
kind: Service
metadata:
  name: kubeclarity-postgres
  labels:
    app: kubeclarity-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: kubeclarity-postgres
