# platform-tools/kubeclarity/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# include base namespace so namespace resource is created
resources:
  - ../../base

helmCharts:
  - name: kubeclarity
    repo: https://openclarity.github.io/kubeclarity
    version: "2.23.3"      # pin the chart version per release (recommended)
    releaseName: kubeclarity
    valuesFile: values.yaml

# ensure everything is deployed to the kubeclarity namespace
namespace: kubeclarity

