# platform-tools/kubeclarity/overlays/stage/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

helmCharts:
  - name: kubeclarity
    repo: https://openclarity.github.io/kubeclarity
    version: "2.23.3"
    releaseName: kubeclarity
    valuesFile: values.yaml

namespace: kubeclarity
