apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: platform-tools

  source:
    repoURL: "https://github.com/DEL-ORG/valdes-argo-k.git"   # <- your Git repo
    targetRevision: HEAD
    path: platform-tools/external-secrets/base                # <- path in your repo
    # NOTE: NO chart / NO repoURL (Helm) at top-level when using path.

  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

