apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform-tools
spec:
  project: platform-tools

  # SOURCE: repoURL, targetRevision, and either path (git) or chart (helm repo)
  source:
    # this is the Git repo where your kustomize/values live (the repo argocd will read)
    repoURL: https://github.com/DEL-ORG/valdes-argo-k.git
    targetRevision: HEAD
    path: platform-tools/external-secrets/base
    chart: 'external-secrets'              
    repoURL: 'https://charts.external-secrets.io'  
    helm:
      releaseName: external-secrets-operator
      valueFiles:
        - base-values.yml
        - overlays/dev/values-patch.yml
      # optional helm settings:
      parameters: []
      passCredentials: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
