apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeclarity

resources:
  - namespace.yaml

labels:
  app.kubernetes.io/name: kubeclarity
  app.kubernetes.io/managed-by: argocd-gitops
