apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml

# keep values.yaml alongside for clarity; Kustomize won't modify it but manages the base
configMapGenerator:
  - name: kubeclarity-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
