apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeclarity

resources:
  - ../../base

# Define helmCharts here so valuesFile can be overlay-specific:
helmCharts:
  - name: kubeclarity
    repo: https://openclarity.github.io/kubeclarity
    version: "v2.23.3"
    releaseName: kubeclarity
    namespace: kubeclarity
    valuesFile: values-patch.yaml

labels:
  env: dev
