apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeclarity-dev
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: 'https://github.com/DEL-ORG/valdes-argo-k.git'
    targetRevision: HEAD
    path: 'apps/kubeclarity/overlays/dev'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeclarity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
